#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

home:
  path: /
  controller: App\Controller\HomeController::home

form_orga:
  path: /form-organisateur
  controller: App\Controller\FormController::createOrga

form_groupe:
  path: /form-groupe
  controller: App\Controller\FormController::createGroupe

orga_home:
  path: /home-organisateur
  controller: App\Controller\HomeController::home_orga

groupe_home:
  path: /home-groupe
  controller: App\Controller\HomeController::home_groupe

search_ann:
  path: /recherche-annonce
  controller: App\Controller\HomeController::search_ann

offre:
  path: /offre
  controller: App\Controller\HomeController::offre

form_ann:
  path: /form-annonce
  controller: App\Controller\HomeController::form_ann

form_event:
  path: /form-evenements
  controller: App\Controller\HomeController::form_event

gestion_ann:
  path: /annonce-gestion
  controller: App\Controller\HomeController::gestion_ann

vitrine_event:
  path: /vitrine-event
  controller: App\Controller\HomeController::vit_event

vitrine_groupe:
  path: /vitrine-groupe
  controller: App\Controller\HomeController::vitrine_groupe

avis:
  path: /avis
  controller: App\Controller\HomeController::avis
  
agenda:
  path: /agenda
  controller: App\Controller\HomeController::agenda

admin_home:
  path: /admin/home
  controller: App\Controller\HomeController::admin_home

admin_form:
  path: /admin/sous-form
  controller: App\Controller\HomeController::admin_form








